#!/usr/bin/env bash
set -e

cd $(dirname $0)/test

if [ -z $1 ]; then
    echo "Usage: $(basename $0) <testname>"
    exit 1
fi

if [[ $1 == *.test ]]; then
    name=$1
else
    name="$1.test"
fi

if [ -f $name ]; then
    echo "Error: A test with that name already exists"
    echo "Exiting..."
    exit 5
fi

cat << EOF > $name
/% CODE %/

function ${name%.*}() {
}

/% TREE %/

Program [
  ("${name%.*}", [], Empty)
]

/% RESULT %/

[
  Empty
]

/% END %/
EOF
