#!/usr/bin/env sh 
set -e

cd $(dirname $0)

BIN_DIR="bin"
TEST_BIN_DIR="${BIN_DIR}/test"
GENTEST_BINARY="${BIN_DIR}/gentest"

if ! [ -f ${GENTEST_BINARY} ]; then
    make clean default test
fi

SRC_DIR="src"
TEST_DIR="test"
TEST_SRC_DIR="${TEST_DIR}/generated"

mkdir -p ${TEST_SRC_DIR} ${TEST_BIN_DIR}
for testfile in ${1:-$TEST_DIR/*.test}; do
    filenameext=$(basename ${testfile})
    filename="${filenameext%.*}"
    out_src_file="${TEST_SRC_DIR}/${filename}.ml"
    out_bin_file="${filename}.native"

    ${GENTEST_BINARY} ${testfile} ${out_src_file} && echo "=> Generating test '${filename}'"
    ocamlbuild -use-menhir -use-ocamlfind -I ${TEST_SRC_DIR} ${filename}.native 1>/dev/null
    mv ${out_bin_file} ${TEST_BIN_DIR}
done

set +e # Dont fail if a test fails
failed=()

shopt -s nullglob
test_binaries=(${TEST_BIN_DIR}/*.native)
count=${#test_binaries[@]}
shopt -u nullglob

echo -e "\n:: All tests built. Running them now!\n"
for exe in ${test_binaries[@]}; do
    filename=$(basename $exe)
    testname=${filename%.*}
    echo -ne "=> Running test '${testname}': "

    if testoutput="$($exe 2>&1)"; then
        echo "PASS!"
    else
        echo "FAIL!"
        echo "$testoutput"
        failed+=("$testname")
    fi
done

failcount=${#failed[@]}
echo -e "\nTest summary:"
echo -e "\t$((count - failcount)) passed."
[ $failcount -gt 0 ] && echo -e "\t$((failcount)) failed: ${failed[@]}" || true
