#!/usr/bin/env sh 
set -e

cd $(dirname $0)

BIN_DIR="bin"
TEST_BIN_DIR="${BIN_DIR}/test"
GENTEST_BINARY="${BIN_DIR}/testing"

if ! [ -f ${GENTEST_BINARY} ]; then
    make clean default test
fi

SRC_DIR="src"
TEST_SRC_DIR="${SRC_DIR}/test/generated"

mkdir -p ${TEST_SRC_DIR} ${TEST_BIN_DIR}
for testfile in ${1:-test/*.test}; do
    filenameext=$(basename ${testfile})
    filename="${filenameext%.*}"
    out_src_file="${TEST_SRC_DIR}/${filename}.ml"
    out_bin_file="${filename}.native"

    echo $out_src_file

    ${GENTEST_BINARY} ${testfile} ${out_src_file} && echo "=> Test ${filename} generated"
    ocamlbuild -use-menhir -use-ocamlfind ${filename}.native
    mv ${out_bin_file} ${TEST_BIN_DIR}
done

echo -e "\n:: All tests built. Running them now!"
for exe in ${TEST_BIN_DIR}/*.native; do
    echo -ne "\n=> Testing: $(basename ${exe}): "
    ${exe}
done

